[package]
name = "xtask-build"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.197", features = ["derive"] }
octocrab = "=0.37.0"
tokio = { version = "1.36.0", features = ["macros"] }

[dev-dependencies]
