[package]
name = "xtask-build"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.197", features = ["derive"] }

[dev-dependencies]
ureq = { version = "2.9.6", features = ["json"] }
