[alias]
serve-site = "run --release --verbose --manifest-path crates/zola/Cargo.toml --bin zola -- serve"
build-site = "run --release --verbose --manifest-path crates/zola/Cargo.toml --bin zola -- build"
