name: Release content

on:
  push:
    tags: "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Generate website
      run: cargo build-site
    - name: Create tarball
      run: tar -czf ../www.paulmin.nl.static.tar.gz --owner=0 --group=0 --no-same-owner --no-same-permissions .
      working-directory: "public"
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "www.paulmin.nl.static.tar.gz"

